---
title: "Hw_5"
author: "Prothila"
date: "11/30/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readr)
library(tidyverse)
library(knitr)
homicide <- read.csv('../data/homicide-data.csv') %>% 
  mutate(city_name = paste(city,state, sep = ",")) 
head(homicide)
```

```{r}
Arrest_of_Grey<- homicide %>% 
  filter(victim_last == "GREY", city =="Baltimore")

```

```{r}
library(lubridate)
Baltimore <- homicide %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  filter(city_name == 'Baltimore,MD') %>% 
  group_by(date = floor_date(reported_date, 'month')) %>% 
  summarize(homicide = n())
head(Baltimore)
```
```{r}
Baltimore$month <- format (as.Date(Baltimore$date, format = "%y/%m/%d"), "%m")
Baltimore$month <- as.numeric(Baltimore$month)
Baltimore <- Baltimore %>% 
  mutate(season = case_when(month >=5 & month <=10 ~'Summer',
                            month <5 ~ 'Winter',
                            month >10 ~'Winter'))
head(Baltimore)
```

```{r}
library(ggplot2)
library(ggthemes)
Baltimore %>% 
  ggplot()+
  geom_bar(aes(x= date, weight = homicide, fill= season))+
  geom_smooth(aes(x= date, y = homicide), color= 'blue', se=FALSE, size =1, span =0.1) +
  scale_fill_manual(values = c('Summer'= 'azure3', 'Winter' = 'lightblue')) +
  geom_vline (xintercept = as.numeric(as.Date('2015-04-30')), linetype= 'longdash', col= 'red')  + 
  annotate("text", x= as.Date('2015-04-30'), y = 45, 
           label = "Arrest of \n Freddie Grey", color ='azure3', hjust = 1, size = 4) +
  ggtitle("Homicides in Baltimore, MD") +
  xlab('Date') +
  ylab('Monthly homicides') +
  theme_dark()
```

